/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dominio.Pedidos;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import negocio.PersistenciaException;
import negocioDAO.PedidoDAO;
import persistenciaBD.ConexionBD;
import persistenciaDAO.IPedidoDAO;
import servicios.GestionEntregas;

/**
 *
 * @author Oscar Quintana
 */
public class PanelEntregas extends javax.swing.JFrame {

    private final IPedidoDAO pedidoDAO;
    private final GestionEntregas servicioEntregas;

    public PanelEntregas() {
        this.pedidoDAO = new PedidoDAO(new ConexionBD());
        this.servicioEntregas = new GestionEntregas(pedidoDAO);

        initComponentsCustom();

        configurarTabla();
        cargarPedidosListos();

        this.setLocationRelativeTo(null);
        this.setTitle("Pizzería - Gestión de Entregas");
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Pedido");
        modelo.addColumn("Cliente");
        modelo.addColumn("Total ($)");
        modelo.addColumn("Estado");
        tablaPedidos.setModel(modelo);
    }

    private void cargarPedidosListos() {
        try {
            List<Pedidos> lista = pedidoDAO.buscarPedidosListos();
            DefaultTableModel modelo = (DefaultTableModel) tablaPedidos.getModel();
            modelo.setRowCount(0);

            for (Pedidos p : lista) {
                Object[] fila = {
                        p.getIdPedido(),
                        "ID: " + p.getIdCliente(),
                        p.getTotal(),
                        p.getEstadoPedido()
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar pedidos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponentsCustom() {
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        ConfirmarEntregaYPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jLabel1.setText("Gestión de Entregas - PIZZERIA");

        jScrollPane2.setViewportView(tablaPedidos);

        ConfirmarEntregaYPago.setText("Confirmar Entrega y Pago");
        ConfirmarEntregaYPago.addActionListener(evt -> ConfirmarEntregaYPagoActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ConfirmarEntregaYPago, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ConfirmarEntregaYPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        ConfirmarEntregaYPago = new javax.swing.JButton();

        jLabel1.setText("Gestión de Entregas");

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(tablaPedidos);

        ConfirmarEntregaYPago.setText("Confirmar Entrega y Pago");
        ConfirmarEntregaYPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarEntregaYPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(ConfirmarEntregaYPago)
                                .addGap(129, 129, 129))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(ConfirmarEntregaYPago)
                                                .addGap(140, 140, 140))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarEntregaYPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarEntregaYPagoActionPerformed
        int filaSeleccionada = tablaPedidos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un pedido de la tabla.");
            return;
        }//GEN-LAST:event_ConfirmarEntregaYPagoActionPerformed
        try {
            int idPedido = (int) tablaPedidos.getValueAt(filaSeleccionada, 0);
            float total = (float) tablaPedidos.getValueAt(filaSeleccionada, 2);
            String estado = (String) tablaPedidos.getValueAt(filaSeleccionada, 3);

            Pedidos pedido = new Pedidos();
            pedido.setIdPedido(idPedido);
            pedido.setTotal(total);
            pedido.setEstadoPedido(estado);

            String[] opciones = {"Efectivo", "Tarjeta"};
            int respuesta = JOptionPane.showOptionDialog(this, "¿Método de pago?", "Pago",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

            if (respuesta == -1) return;
            String metodo = opciones[respuesta];

            servicioEntregas.entregarPedido(pedido, metodo);

            JOptionPane.showMessageDialog(this, "Entrega y pago registrados exitosamente.");
            cargarPedidosListos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la entrega: " + e.getMessage());
        }
    }

    private javax.swing.JButton ConfirmarEntregaYPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaPedidos;
}
